os: Visual Studio 2015

clone_folder: c:\projects\gameboycore-python

branches:
  only:
    - master
    - multiple-versions

environment:
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_LIB_DIR: lib32-msvc-14.0

  password:
    secure: bkWnSpT47YhbxGA3RUIBTcvQOPbPG5ziYsQtLOE1L/c=

  matrix:
    - PYTHON_ROOT: "C:\\Python33"
      PYTHON_VERSION: 3.3
    - PYTHON_ROOT: "C:\\Python34"
      PYTHON_VERSION: 3.4
    - PYTHON_ROOT: "C:\\Python35"
      PYTHON_VERSION: 3.5

init:
  - set PATH=%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PYTHON_ROOT%\Lib;%PATH%

install:
  - python --version
  - pip --version
  - pip install setuptools --upgrade
  - pip install wheel

before_build:
  - cd c:\projects\gameboycore-python
  - "echo using python : %PYTHON_VERSION% : %PYTHON_ROOT% : %PYTHON_ROOT%\include : %PYTHON_ROOT%\libs ; > C:\Libraries\boost_1_60_0\user-config.jam"
  - cd C:\Libraries\boost_1_60_0
  - bootstrap
  - bjam --with-python python-debugging=off threading=multi variant=release link=static
  - dir C:\Libraries\boost_1_60_0\stage\lib

build_script:
  - cd c:\projects\gameboycore-python
  - git submodule init
  - git submodule update
  - python setup.py build

deploy_script:
  - set HOME=%USERPROFILE%
  - echo [pypirc] > %HOME%\\.pypirc
  - echo servers=pypi >> %HOME%\\.pypirc
  - echo [server-login] >> %HOME%\\.pypirc
  - echo username:nnarain >> %HOME%\\.pypirc
  - "echo password:%password% >> %HOME%\\.pypirc"
  - python setup.py sdist bdist_egg bdist_wheel #upload
